### ISSUE TITLE
Create an API endpoint for send system message

### ISSUE THREAD

**Issue by diangogav** [diangogav/EDOpro-server-ts#38]
## Description
We need an API endpoint to send server messages to clients using the `ServerMessageClientMessage`...

## Tasks
- [x] Create `ServerMessagesController` with the POST endpoint and implement the send message logic.

## Acceptance Criteria
- [x] If a POST request is made to the `/server/message` endpoint with the body `{ "message": "lorem ipsum" }`, it should send "lorem ipsum" to the clients as a message.

**Comment by DembaIsCodingg** [comment]
in what folder should i implement this code ?

**Comment by diangogav** [comment]
> Hello there, this is one of my first open source contribution. Nice to meet you, in what folder should i implement this code ?


Hello, @DembaIsCoding, nice to meet you, and thank you for your interest in this project. In the pull request, I will include my suggestions. :raised_hands:

**Comment by diegofcornejo** [comment]
The issue has been resolved in pull request #92.

**Comment by diangogav** [comment]
Thanks @diegofcornejo <3
